AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "bin/bundle"
    - "Guardfile"
    - "config/environments/development.rb"
    - "node_modules/**/*"
    - "config/application.rb"
    - "db/schema.rb"
    - "app/spec"
    - "db/migrate/20210421203610_create_active_storage_tables.active_storage.rb"

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Naming/PredicateName:
  Enabled: false
